Corrige build 615.
Corrigido

    AttributeError: 'super' object has no attribute 'replace_with_objects'

baseado em https://github.com/plonegovbr/brasil.gov.tiles/pull/128#issuecomment-103066159

O erro

    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

persiste e parece ser um erro do Selenium como visto em https://github.com/plonegovbr/brasil.gov.tiles/pull/128#issuecomment-102429107,
ainda sem solução.