Corrige build 615 (StaleElementReferenceException)
Corrige erro

    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

Baseado em

http://www.coactivate.org/projects/barcelona-sprint/lists/barcelona-sprint-discussion/archive/2013/02/1360419825199/forum_view

Atualização das versões dos pacotes robots e selenium não resolveram o
erro por completo, daí a necessidade da customização nesse commit.