Corrige build 615 parcialmente.
Corrige (em partes) https://travis-ci.org/plonegovbr/brasil.gov.tiles/builds/62702448 após
recomendação em https://github.com/plonegovbr/brasil.gov.tiles/issues/26#issuecomment-102427925

O erro

    StaleElementReferenceException: Message: Element not found in the cache - perhaps the page has changed since it was looked up

persiste e parece ser um erro do Selenium como visto em https://github.com/plonegovbr/brasil.gov.tiles/pull/128#issuecomment-102429107,
ainda sem solução;

O erro

    brasil.gov.tiles/src/brasil/gov/tiles/tiles/destaque.py", line 108, in replace_with_objects
        super(DestaqueTile, self).replace_with_objects(uids)  # check permission  # NOQA
    AttributeError: 'super' object has no attribute 'replace_with_objects'

passou a ocorrer depois da adição do TestTileMixin e precisa ser
estudado.